import os

import sib_api_v3_sdk
from sib_api_v3_sdk.rest import ApiException


async def send_email(to: str, subject: str, summary: str) -> None:
    html_body = f"""
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <style>
    body {{ font-family: Arial, sans-serif; background: #f4f4f4; margin: 0; padding: 20px; }}
    .card {{
      background: #ffffff;
      border: 3px solid #000;
      max-width: 680px;
      margin: 0 auto;
      padding: 32px;
      box-shadow: 6px 6px 0px #000000;
    }}
    .badge {{
      display: inline-block;
      background: #2563EB;
      color: #fff;
      font-weight: 900;
      font-size: 11px;
      letter-spacing: 2px;
      text-transform: uppercase;
      padding: 4px 12px;
      border: 2px solid #000;
      margin-bottom: 20px;
    }}
    h1 {{
      font-size: 22px;
      font-weight: 900;
      text-transform: uppercase;
      letter-spacing: 1px;
      margin: 0 0 16px;
      border-bottom: 3px solid #000;
      padding-bottom: 12px;
    }}
    .summary {{ font-size: 15px; line-height: 1.8; color: #1a1a1a; white-space: pre-wrap; }}
    .footer {{
      margin-top: 24px;
      padding-top: 12px;
      border-top: 2px solid #000;
      font-size: 11px;
      color: #666;
      text-transform: uppercase;
      letter-spacing: 1px;
    }}
  </style>
</head>
<body>
  <div class="card">
    <div class="badge">Rabbitt AI — Sales Insight</div>
    <h1>Executive Sales Summary</h1>
    <div class="summary">{summary}</div>
    <div class="footer">Generated by Sales Insight Automator · Powered by Groq</div>
  </div>
</body>
</html>
"""

    configuration = sib_api_v3_sdk.Configuration()
    configuration.api_key["api-key"] = os.environ["BREVO_API_KEY"]

    api_instance = sib_api_v3_sdk.TransactionalEmailsApi(
        sib_api_v3_sdk.ApiClient(configuration)
    )

    sender_email = os.environ.get("BREVO_SENDER_EMAIL", "ayushchauhan1164@gmail.com")
    sender_name = os.environ.get("BREVO_SENDER_NAME", "Sales Insight Automator")

    send_smtp_email = sib_api_v3_sdk.SendSmtpEmail(
        to=[{"email": to}],
        sender={"name": sender_name, "email": sender_email},
        subject=subject,
        html_content=html_body,
    )

    try:
        api_instance.send_transac_email(send_smtp_email)
    except ApiException as exc:
        raise RuntimeError(f"Brevo email failed: {exc.status} — {exc.body}") from exc
